# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-09 05:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0011_admin_related_improvements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='new_status',
            field=models.IntegerField(blank=True, choices=[(1, 'Abierto'), (2, 'Reabierto'), (3, 'Resuelto'), (4, 'Cerrado'), (5, 'Duplicado')], help_text='If the status was changed, what was it changed to?', null=True, verbose_name='New Status'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='helpdesk.Ticket', verbose_name='Ticket'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.IntegerField(choices=[(1, 'Abierto'), (2, 'Reabierto'), (3, 'Resuelto'), (4, 'Cerrado'), (5, 'Duplicado')], default=1, verbose_name='Status'),
        ),
    ]
