# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-02 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0012_auto_20160609_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=b'', verbose_name='Imagen'),
        ),
    ]
