# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-02 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0013_followup_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='followup', verbose_name='Imagen'),
        ),
    ]
