# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-02 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0015_auto_20160702_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='image',
            field=models.ImageField(default='', upload_to='followup/', verbose_name='Imagen'),
        ),
    ]
