# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-06 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0016_auto_20160702_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='file1',
            field=models.FileField(default='', upload_to='followup/', verbose_name='Documento 1'),
        ),
        migrations.AddField(
            model_name='followup',
            name='file10',
            field=models.FileField(default='', upload_to='followup/', verbose_name='Documento 10'),
        ),
        migrations.AddField(
            model_name='followup',
            name='file2',
            field=models.FileField(default='', upload_to='followup/', verbose_name='Documento 2'),
        ),
        migrations.AddField(
            model_name='followup',
            name='file3',
            field=models.FileField(default='', upload_to='followup/', verbose_name='Documento 3'),
        ),
        migrations.AddField(
            model_name='followup',
            name='file4',
            field=models.FileField(default='', upload_to='followup/', verbose_name='Documento 4'),
        ),
        migrations.AddField(
            model_name='followup',
            name='file5',
            field=models.FileField(default='', upload_to='followup/', verbose_name='Documento 5'),
        ),
        migrations.AddField(
            model_name='followup',
            name='file6',
            field=models.FileField(default='', upload_to='followup/', verbose_name='Documento 6'),
        ),
        migrations.AddField(
            model_name='followup',
            name='file7',
            field=models.FileField(default='', upload_to='followup/', verbose_name='Documento 7'),
        ),
        migrations.AddField(
            model_name='followup',
            name='file8',
            field=models.FileField(default='', upload_to='followup/', verbose_name='Documento 8'),
        ),
        migrations.AddField(
            model_name='followup',
            name='file9',
            field=models.FileField(default='', upload_to='followup/', verbose_name='Documento 9'),
        ),
    ]
