# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-13 02:02
from __future__ import unicode_literals

from django.db import migrations, models
import helpdesk.models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0018_auto_20160705_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='file1',
            field=models.FileField(blank=True, default='', null=True, upload_to=helpdesk.models.followup_files_name, verbose_name='Documento 1'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='file10',
            field=models.FileField(blank=True, default='', null=True, upload_to=helpdesk.models.followup_files_name, verbose_name='Documento 10'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='file2',
            field=models.FileField(blank=True, default='', null=True, upload_to=helpdesk.models.followup_files_name, verbose_name='Documento 2'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='file3',
            field=models.FileField(blank=True, default='', null=True, upload_to=helpdesk.models.followup_files_name, verbose_name='Documento 3'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='file5',
            field=models.FileField(blank=True, default='', null=True, upload_to=helpdesk.models.followup_files_name, verbose_name='Documento 5'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='file6',
            field=models.FileField(blank=True, default='', null=True, upload_to=helpdesk.models.followup_files_name, verbose_name='Documento 6'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='file7',
            field=models.FileField(blank=True, default='', null=True, upload_to=helpdesk.models.followup_files_name, verbose_name='Documento 7'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='file8',
            field=models.FileField(blank=True, default='', null=True, upload_to=helpdesk.models.followup_files_name, verbose_name='Documento 8'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='file9',
            field=models.FileField(blank=True, default='', null=True, upload_to=helpdesk.models.followup_files_name, verbose_name='Documento 9'),
        ),
        migrations.AlterField(
            model_name='followup',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to=helpdesk.models.followup_files_name, verbose_name='Imagen'),
        ),
    ]
