# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-13 02:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clients', models.ManyToManyField(blank=True, related_name='projects', to='client.Client')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.Enterprise')),
            ],
        ),
    ]
