# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-04 01:58
from __future__ import unicode_literals

import client.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=55, verbose_name='Nombre')),
                ('position', models.CharField(default='', max_length=55, verbose_name='Puesto')),
                ('email', models.EmailField(default='', max_length=254, verbose_name='Correo electr\xf3nico')),
                ('phone_number', models.CharField(default='', max_length=20, verbose_name='Tel\xe9fono')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='birth_date',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='client',
            name='profile_pic',
            field=models.FileField(blank=True, null=True, upload_to=client.models.client_files_name, verbose_name='Foto de perfil'),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='city',
            field=models.CharField(default='', max_length=55, verbose_name='Ciudad-Estado'),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='direction',
            field=models.CharField(default='', max_length=255, verbose_name='Direcci\xf3n'),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='phone_number_1',
            field=models.CharField(default='', max_length=20, verbose_name='Tel\xe9fono'),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='phone_number_2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Tel\xe9fono 2'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='enterprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='client.Enterprise'),
        ),
    ]
