# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-25 21:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20160803_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='estatus',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Contacto'), (2, 'Contrato Firmado'), (3, 'Revisi\xf3n de Contrato'), (4, 'Pago Pendiente'), (5, 'Fin de Relaci\xf3n')], default=1, verbose_name='Estatus'),
        ),
        migrations.AddField(
            model_name='project',
            name='estatus',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Levantamiento'), (2, 'Dise\xf1o'), (3, 'Retroalimentaci\xf3n de cliente'), (4, 'Implementaci\xf3n'), (5, 'Mantenimiento'), (6, 'DEMO'), (7, 'Activo'), (8, 'Alerta')], default=1, verbose_name='Estatus'),
        ),
        migrations.AlterField(
            model_name='project',
            name='enterprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='client.Enterprise'),
        ),
    ]
