# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-13 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_auto_20160825_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='cp',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='C\xf3digo Postal'),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='nombre_fiscal',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='Nombre Fiscal'),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='rfc',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='RFC'),
        ),
        migrations.AddField(
            model_name='project',
            name='nombre_encargado',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='Nombre Encargado'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Demo'), (2, 'Laboratorio'), (3, 'Clinica'), (4, 'Hospital')], default=1, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='direction',
            field=models.CharField(default='', max_length=255, verbose_name='Direcci\xf3n Fiscal'),
        ),
    ]
