# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-17 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_auto_20161203_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='email_contact',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Correo de contacto'),
        ),
        migrations.AddField(
            model_name='project',
            name='cedula_encargado',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='C\xe9dula Profesional'),
        ),
        migrations.AddField(
            model_name='project',
            name='correo_encargado',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Correo Encargado'),
        ),
        migrations.AddField(
            model_name='project',
            name='telefono_encargado',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='Telefono Encargado'),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='city',
            field=models.CharField(default='', max_length=55, verbose_name='Colonia / Ciudad / Estado'),
        ),
        migrations.AlterField(
            model_name='project',
            name='nombre_encargado',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre Responsable'),
        ),
    ]
