# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-05 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_auto_20161217_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='email_contact',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Correo de contacto'),
        ),
    ]
