# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-07 21:08
from __future__ import unicode_literals

import client.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_auto_20170305_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='image_logo',
            field=models.ImageField(blank=True, null=True, upload_to=client.models.client_logo_name, verbose_name='Logotipo'),
        ),
    ]
