# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 21:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Arduino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('arduino_token', models.CharField(max_length=20, unique=True)),
                ('location', models.CharField(max_length=255)),
                ('available_sensors', models.SmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArduinoSensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('index', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('arduino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arduino.Arduino', to_field='arduino_token')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('prefix', models.CharField(max_length=2, unique=True)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('arduino_sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_data', related_query_name='sensor_data', to='arduino.ArduinoSensor')),
            ],
        ),
        migrations.AddField(
            model_name='arduinosensor',
            name='arduino_sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arduino.Sensor'),
        ),
        migrations.AddField(
            model_name='arduino',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arduino.Project'),
        ),
        migrations.AddField(
            model_name='arduino',
            name='sensors',
            field=models.ManyToManyField(through='arduino.ArduinoSensor', to='arduino.Sensor'),
        ),
    ]
