# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arduino', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arduinosensor',
            name='data_key',
            field=models.CharField(default='x', max_length=20),
            preserve_default=False,
        ),
    ]
