# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-18 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arduino', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='epoch',
            field=models.PositiveIntegerField(default=0, null=True),
        )
    ]
