# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-09 05:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arduino', '0002_arduinosensor_data_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arduino',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arduinos', to='arduino.Project'),
        ),
        migrations.AlterField(
            model_name='arduinosensor',
            name='arduino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arduino_sensors', to='arduino.Arduino', to_field='arduino_token'),
        ),
    ]
