# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-30 01:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_project'),
        ('arduino', '0005_auto_20160712_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='arduino',
            name='projectc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='arduinos', to='client.Project'),
            preserve_default=False,
        ),
    ]
