# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-27 02:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arduino', '0005_auto_20161114_2321'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='EmailSend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.CharField(max_length=510)),
                ('to', models.CharField(max_length=510)),
                ('subject', models.CharField(max_length=55)),
                ('text_content', models.TextField()),
                ('html_content', models.TextField()),
                ('sended_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'get_latest_by': 'sended_at',
            },
        ),
        migrations.CreateModel(
            name='SensorAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('active', models.BooleanField(default=True)),
                ('arduino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='arduino.Arduino')),
                ('email_sends', models.ManyToManyField(related_name='email_sends', to='arduino.EmailSend')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='arduino.ArduinoSensor')),
            ],
        ),
        migrations.AlterModelOptions(
            name='sensordata',
            options={'get_latest_by': 'epoch'},
        ),
        migrations.AlterField(
            model_name='sensortype',
            name='subfix',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Sufijo'),
        ),
        migrations.AddField(
            model_name='sensoralert',
            name='sensor_data',
            field=models.ManyToManyField(through='arduino.AlertData', to='arduino.SensorData'),
        ),
        migrations.AddField(
            model_name='alertdata',
            name='alert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arduino.SensorAlert'),
        ),
        migrations.AddField(
            model_name='alertdata',
            name='data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arduino.SensorData'),
        ),
    ]
