# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-27 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arduino', '0006_auto_20161126_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arduino',
            name='arduino_token',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
