# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-30 01:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arduino', '0008_auto_20160729_2052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arduino',
            old_name='projectc',
            new_name='project',
        ),
    ]
