# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-28 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arduino', '0009_remove_arduinoalert_sensor'),
    ]

    operations = [
        migrations.AddField(
            model_name='arduinoalert',
            name='sensors_in_alert',
            field=models.ManyToManyField(to='arduino.ArduinoSensor'),
        ),
        migrations.AlterField(
            model_name='arduinoalert',
            name='email_sends',
            field=models.ManyToManyField(to='arduino.EmailSend'),
        ),
    ]
