# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-30 03:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arduino', '0009_auto_20160729_2055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arduinosensor',
            old_name='arduino_sensor',
            new_name='sensor_type',
        ),
    ]
