# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-30 03:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arduino', '0010_auto_20160729_2230'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sensor',
            new_name='SensorType',
        ),
    ]
