# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-03 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_auto_20161203_1414'),
        ('arduino', '0010_auto_20161127_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre Refrigerador')),
                ('equipment_model', models.CharField(blank=True, max_length=255, null=True, verbose_name='Modelo Refrigerador')),
                ('equipment_brand', models.CharField(blank=True, max_length=255, null=True, verbose_name='Marca Refrigerador')),
                ('equipment_buydate', models.CharField(blank=True, max_length=255, null=True, verbose_name='Fecha de Compra')),
                ('equipment_serial', models.CharField(blank=True, max_length=255, null=True, verbose_name='No. Serie')),
                ('equipment_size', models.CharField(blank=True, max_length=255, null=True, verbose_name='Medidas del equipo')),
                ('equipment_comments', models.CharField(blank=True, max_length=255, null=True, verbose_name='Comentarios del equipo')),
                ('equipment_notes', models.CharField(blank=True, max_length=255, null=True, verbose_name='Notas Adicionales')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', related_query_name='equipments', to='client.Project')),
            ],
        ),
        migrations.AddField(
            model_name='arduino',
            name='correos_alertas',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Correos para alertas'),
        ),
        migrations.AddField(
            model_name='arduinosensor',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='arduino.SensorEquipment'),
        ),
    ]
