# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-30 05:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arduino', '0011_auto_20160729_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arduinosensor',
            name='arduino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arduino.Arduino'),
        ),
    ]
