# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-04 01:58
from __future__ import unicode_literals

import arduino.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arduino', '0012_auto_20160730_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='arduinosensor',
            name='max_value',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='Valor m\xe1ximo permitido'),
        ),
        migrations.AddField(
            model_name='arduinosensor',
            name='min_value',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='Valor m\xednimo permitido'),
        ),
        migrations.AddField(
            model_name='sensortype',
            name='data_image',
            field=models.FileField(blank=True, null=True, upload_to=arduino.models.sensortype_files_name, verbose_name='Imagen del sensor'),
        ),
        migrations.AddField(
            model_name='sensortype',
            name='data_sheet',
            field=models.FileField(blank=True, null=True, upload_to=arduino.models.sensortype_files_name, verbose_name='Ficha t\xe9cnica'),
        ),
        migrations.AddField(
            model_name='sensortype',
            name='data_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Booleano'), (1, 'Decimal'), (2, 'Entero'), (3, 'Texto')], default=1),
        ),
        migrations.AddField(
            model_name='sensortype',
            name='model',
            field=models.CharField(default='', max_length=255, verbose_name='Modelo de sensor'),
        ),
        migrations.AlterField(
            model_name='sensortype',
            name='description',
            field=models.CharField(default='', max_length=255, verbose_name='Descripci\xf3n'),
        ),
        migrations.AlterField(
            model_name='sensortype',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='sensortype',
            name='prefix',
            field=models.CharField(default='', max_length=2, unique=True, verbose_name='Prefijo'),
        ),
    ]
