# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-17 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arduino', '0013_auto_20161217_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='arduino',
            name='modelo_transmisor',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Modelo del transmisor'),
        ),
        migrations.AlterField(
            model_name='arduino',
            name='correos_alertas',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Correos para alertas (Separados por , )'),
        ),
        migrations.AlterField(
            model_name='arduino',
            name='location',
            field=models.CharField(max_length=255, verbose_name='Ubicaci\xf3n Fisica del Transmisor'),
        ),
        migrations.AlterField(
            model_name='arduino',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre del Transmisor'),
        ),
    ]
