# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-21 23:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('arduino', '0013_auto_20160803_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensortype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 8, 21, 23, 53, 40, 12406, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensortype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 8, 21, 23, 53, 48, 173238, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
