# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-25 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arduino', '0014_auto_20160821_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='arduino',
            name='estatus',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Dise\xf1o'), (2, 'Construcci\xf3n'), (3, 'Implementaci\xf3n'), (4, 'Mantenimiento/Pruebas'), (5, 'Producci\xf3n'), (6, 'Fallo de Sistema')], default=1, verbose_name='Estatus'),
        ),
    ]
