# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-18 03:28
from __future__ import unicode_literals

import arduino.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arduino', '0015_auto_20161217_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_archivo', models.PositiveSmallIntegerField(choices=[(1, 'PDF'), (2, 'CSV'), (3, 'XLSX')], default=1, verbose_name='Tipo de Archivo')),
                ('tipo_reporte', models.PositiveSmallIntegerField(choices=[(1, 'Reporte de Registros'), (2, 'Reporte de Alertas')], default=1, verbose_name='Tipo de Reporte')),
                ('fecha_inicial', models.PositiveIntegerField()),
                ('fecha_final', models.PositiveIntegerField()),
                ('archivo', models.FileField(upload_to=arduino.models.report_files_name)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arduino.ArduinoSensor')),
            ],
        ),
    ]
