# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-18 04:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arduino', '0019_auto_20170117_2257'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-created_at']},
        ),
    ]
