# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-05 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arduino', '0020_auto_20170117_2259'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertObservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('causa_observacion', models.PositiveSmallIntegerField(choices=[(1, 'Pendiente de Llenado'), (2, 'Mantenimiento'), (3, 'Abastecimiento de material'), (4, 'Falla electrica'), (5, 'Cerrado Inapropiado')], default=1, verbose_name='Causa del evento')),
                ('titulo_observacion', models.TextField(blank=True, max_length=1024, null=True, verbose_name='Nombre Observacion')),
                ('accion_observacion', models.TextField(blank=True, max_length=1024, null=True, verbose_name='Accion Correctiva')),
                ('nota_observacion', models.TextField(blank=True, max_length=1024, null=True, verbose_name='Nota Adicional')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
