# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-12 00:41
from __future__ import unicode_literals

import arduino.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('arduino', '0021_alertobservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_file_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='updated_at',
            field=models.DateField(auto_now=True, default=datetime.datetime(2017, 3, 12, 0, 41, 38, 535943, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to=arduino.models.report_files_name),
        ),
    ]
