# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-12 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arduino', '0022_auto_20170311_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
