# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-20 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arduino', '0023_auto_20170311_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensortype',
            name='decimales',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='sensortype',
            name='magnitud',
            field=models.CharField(default='', max_length=255, verbose_name='Magnitud de la medicion'),
        ),
        migrations.AddField(
            model_name='sensortype',
            name='simbolo',
            field=models.CharField(default='', max_length=30, verbose_name='Simbolo de la magnitud'),
        ),
    ]
