#!/bin/bash

NAME="daphne_app"                                 # Name of the application
DJANGODIR=/home/manto/sensait/sensait_django      # Django project directory
SOCKFILE=/home/manto/sensait/run/daphne.sock      # we will communicte using this unix socket
USER=manto                                        # the user to run as
GROUP=manto                                       # the group to run as
#NUM_WORKERS=3                                    # how many worker processes should Gunicorn spawn
DJANGO_SETTINGS_MODULE=ardsensor.settings         # which settings file should Django use
DJANGO_ASGI_MODULE=ardsensor.asgi                 # WSGI module name

echo "Starting $NAME as `whoami`"

# Activate the virtual environment
cd $DJANGODIR
source /home/manto/.venvs/sensait_channels/bin/activate
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH

# Create the run directory if it doesn't exist
RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR

# Start your Django Unicorn
# Programs meant to be run under supervisor should not daemonize themselves (do not use --daemon)
exec daphne -u $SOCKFILE ${DJANGO_ASGI_MODULE}:channel_layer